Name: Environment
Description: Environment is the primary object intended for storing active
  objects in the place.
Category: game
BaseType: Instance
Properties:
  - Name: CurrentCamera
    Type:
      Name: Camera
      IsOptional: false
    IsAccessibleByScripts: true
    IsReadOnly: false
    IsStatic: false
    ObsoletionInfo: null
    Description: Determines the current camera which the player is using to view the world.
  - Name: Gravity
    Type:
      Name: Vector3
      IsOptional: false
    IsAccessibleByScripts: true
    IsReadOnly: false
    IsStatic: false
    ObsoletionInfo: null
    Description: The direction and strength of gravity in the world.
  - Name: PartDestroyHeight
    Type:
      Name: number
      IsOptional: false
    IsAccessibleByScripts: true
    IsReadOnly: false
    IsStatic: false
    ObsoletionInfo: null
    Description: The height at which unanchored parts are destroyed when they fall below it.
  - Name: AutoGenerateNavMesh
    Type:
      Name: boolean
      IsOptional: false
    IsAccessibleByScripts: true
    IsReadOnly: false
    IsStatic: false
    ObsoletionInfo: null
    Description: Determines whether or not to automatically build a navigation mesh
      for NPC pathfinding. This property is disabled by default so there are no
      performance issues with larger maps.
Methods:
  - Name: Raycast
    Returns:
      - Name: RayResult
        IsOptional: true
    Parameters:
      - Type:
          Name: Vector3
          IsOptional: false
        Name: origin
        DefaultValue: null
      - Type:
          Name: Vector3
          IsOptional: false
        Name: direction
        DefaultValue: null
      - Type:
          Name: number
          IsOptional: true
        Name: maxDistance
        DefaultValue: "10000"
      - Type:
          ElementType:
            Name: Instance
            IsOptional: false
          Name: Array
          IsOptional: true
        Name: ignoreList
        DefaultValue: null
      - Type:
          Name: number
          IsOptional: true
        Name: passthroughMask
        DefaultValue: "0"
    IsAsync: false
    IsStatic: false
    IsSemiStatic: false
    ObsoletionInfo: null
    Description: Casts a ray from origin with a specified direction and returns a
      RayResult for the first hit object.
  - Name: RaycastAll
    Returns:
      - ElementType:
          Name: RayResult
          IsOptional: false
        Name: Array
        IsOptional: false
    Parameters:
      - Type:
          Name: Vector3
          IsOptional: false
        Name: origin
        DefaultValue: null
      - Type:
          Name: Vector3
          IsOptional: false
        Name: direction
        DefaultValue: null
      - Type:
          Name: number
          IsOptional: true
        Name: maxDistance
        DefaultValue: "1000"
      - Type:
          ElementType:
            Name: Instance
            IsOptional: false
          Name: Array
          IsOptional: true
        Name: ignoreList
        DefaultValue: null
    IsAsync: false
    IsStatic: false
    IsSemiStatic: false
    ObsoletionInfo: null
    Description: Casts a ray from origin with a specified direction and returns a
      RayResult array for all hit objects.
  - Name: RaycastGather
    Returns:
      - ElementType:
          Name: RayResult
          IsOptional: false
        Name: Array
        IsOptional: false
    Parameters:
      - Type:
          Name: Vector3
          IsOptional: false
        Name: origin
        DefaultValue: null
      - Type:
          Name: Vector3
          IsOptional: false
        Name: direction
        DefaultValue: null
      - Type:
          Name: number
          IsOptional: true
        Name: maxDistance
        DefaultValue: "10000"
      - Type:
          ElementType:
            Name: Instance
            IsOptional: false
          Name: Array
          IsOptional: true
        Name: ignoreList
        DefaultValue: null
      - Type:
          Name: number
          IsOptional: true
        Name: passthroughMask
        DefaultValue: "0"
    IsAsync: false
    IsStatic: false
    IsSemiStatic: false
    ObsoletionInfo: null
    Description: Missing Documentation
  - Name: OverlapSphere
    Returns:
      - ElementType:
          Name: Instance
          IsOptional: false
        Name: Array
        IsOptional: false
    Parameters:
      - Type:
          Name: Vector3
          IsOptional: false
        Name: origin
        DefaultValue: null
      - Type:
          Name: number
          IsOptional: false
        Name: radius
        DefaultValue: null
      - Type:
          ElementType:
            Name: Instance
            IsOptional: false
          Name: Array
          IsOptional: true
        Name: ignoreList
        DefaultValue: null
    IsAsync: false
    IsStatic: false
    IsSemiStatic: false
    ObsoletionInfo: null
    Description: Returns a list of instances intersecting with the sphere in the
      given position and radius.
  - Name: OverlapBox
    Returns:
      - ElementType:
          Name: Instance
          IsOptional: false
        Name: Array
        IsOptional: false
    Parameters:
      - Type:
          Name: Vector3
          IsOptional: false
        Name: pos
        DefaultValue: null
      - Type:
          Name: Vector3
          IsOptional: false
        Name: size
        DefaultValue: null
      - Type:
          Name: Vector3
          IsOptional: false
        Name: rot
        DefaultValue: null
      - Type:
          ElementType:
            Name: Instance
            IsOptional: false
          Name: Array
          IsOptional: true
        Name: ignoreList
        DefaultValue: null
    IsAsync: false
    IsStatic: false
    IsSemiStatic: false
    ObsoletionInfo: null
    Description: Returns a list of instances intersecting with the box in the given
      position, size and rotation.
  - Name: RebuildNavMesh
    Returns: []
    Parameters: []
    IsAsync: false
    IsStatic: false
    IsSemiStatic: false
    ObsoletionInfo: null
    Description: Rebuilds the navigation mesh which determines the empty space where
      NPCs can pathfind in.
  - Name: GetPointOnNavMesh
    Returns:
      - Name: Vector3
        IsOptional: false
    Parameters:
      - Type:
          Name: Vector3
          IsOptional: false
        Name: toPoint
        DefaultValue: null
    IsAsync: false
    IsStatic: false
    IsSemiStatic: false
    ObsoletionInfo: null
    Description: Returns a point on the navigation mesh at the given position.
Events: []
IsStatic: true
IsAbstract: false
IsInstantiable: false
StaticAlias: Environment
